//
//  hash.h
//  narcissism
//
//  Created by Scott Brenner on 3/8/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#ifndef narcissism_hash_h
#define narcissism_hash_h

#include <iostream>
#include <string>
#include "simpio.h"

#define MAX_HASH_CODE	10000	// Upper bound for hash codes generated by program
#define Multiplier -1664117991L		// Multiplier used in Hash function

int Hash(std::string s, int maxCode);
int createHash();


#endif
